[package]
name = "zjut-phy-hwk"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["syqwq-OMG"]
license = "MIT"
description = "物理作业解答模板，支持(a)(b)(c)子题编号和物理常数"
repository = "https://github.com/syqwq-OMG/ecnu-math-hwk"
keywords = ["ZJUT", "physics", "homework", "浙江工业大学", "物理"]
categories = ["report"]
exclude = ["pic"]
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "hw.typ"
thumbnail = "thumbnail.png"